# Generated by Django 3.2.1 on 2021-05-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ph_no',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.TextField(default=1),
        ),
    ]
