# Generated by Django 3.2.1 on 2021-05-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='TAGS',
            field=models.CharField(choices=[('MUSIC', 'RELATED TO MUSIC'), ('GAMES', 'RELATED TO GAMES'), ('MEDIA', 'RELATED TO SOCIAL MEDIA'), ('MEDICAL', 'RELATED TO MEDICAL'), ('E-COMMERCE', 'RELATED TO E-COMMERCE'), ('N/A', 'N/A')], default='N/A', max_length=32),
        ),
    ]
