# Generated by Django 3.2.1 on 2021-05-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief',
            field=models.CharField(default='brief detail about the project', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
