# Generated by Django 3.2.1 on 2021-05-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210518_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
