# Generated by Django 3.2.1 on 2021-05-19 09:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_blogcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BLogComment',
            new_name='Ratings',
        ),
    ]
