# Generated by Django 3.2.1 on 2021-05-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_ratings_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='parent',
        ),
    ]
