# Generated by Django 3.2.1 on 2021-05-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210520_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='TAGS',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], default='N/A', max_length=32),
        ),
    ]
