# Generated by Django 3.2.1 on 2021-05-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210521_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Name',
            new_name='Project_name',
        ),
    ]
