# Generated by Django 3.2.1 on 2021-05-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_review_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='post',
            new_name='Post',
        ),
    ]
